"""Change odometer type

Revision ID: 8157825cd63c
Revises: 3b62ae2cc970
Create Date: 2025-08-20 12:56:28.882891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8157825cd63c'
down_revision: Union[str, None] = '3b62ae2cc970'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle', 'odometer',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
                postgresql_using='odometer::integer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle', 'odometer',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
                    postgresql_using='odometer::integer')
    # ### end Alembic commands ###
